export const GET_AUTHORS_FROM_SERVER = "GET_AUTHORS_FROM_SERVER";
//Create
export const CREATE_AUTHOR = "CREATE_AUTHOR";
export const CREATE_AUTHOR_REAL = "CREATE_AUTHOR_REAL"; //Server accept
export const CREATE_AUTHOR_UNDU = "CREATE_AUTHOR_UNDU"; //Server denie
//Delete
export const DELETE_AUTHOR = "DELETE_AUTHOR";
export const DELETE_AUTHOR_REAL = "DELETE_AUTHOR_REAL";
export const DELETE_AUTHOR_UNDU = "DELETE_AUTHOR_UNDU";
//Edit
export const UPDATE_AUTHOR = "UPDATE_AUTHOR";
export const UPDATE_AUTHOR_REAL = "UPDATE_AUTHOR_REAL";
export const UPDATE_AUTHOR_UNDU = "UPDATE_AUTHOR_UNDU";
