export const GET_BOOKS_FROM_SERVER = "GET_BOOKS_FROM_SERVER";
//Create
export const CREATE_BOOK = "CREATE_BOOK";
export const CREATE_BOOK_REAL = "CREATE_BOOK_REAL";
export const CREATE_BOOK_UNDU = "CREATE_BOOK_UNDU";
//Delete
export const DELETE_BOOK = "DELETE_BOOK";
export const DELETE_BOOK_REAL = "DELETE_BOOK_REAL";
export const DELETE_BOOK_UNDU = "DELETE_BOOK_UNDU";
//Edit
export const UPDATE_BOOK = "UPDATE_BOOK";
export const UPDATE_BOOK_REAL = "UPDATE_BOOK_REAL";
export const UPDATE_BOOK_UNDU = "UPDATE_BOOK_UNDU";
