export const GET_HEROES_FROM_SERVER = "GET_HEROES_FROM_SERVER";
//Create
export const CREATE_HERO = "CREATE_HERO";
export const CREATE_HERO_REAL = "CREATE_HERO_REAL";
export const CREATE_HERO_UNDU = "CREATE_HERO_UNDU";
//Delete
export const DELETE_HERO = "DELETE_HERO";
export const DELETE_HERO_REAL = "DELETE_HERO_REAL";
export const DELETE_HERO_UNDU = "DELETE_HERO_UNDU";
//Edit
export const UPDATE_HERO = "UPDATE_HERO";
export const UPDATE_HERO_REAL = "UPDATE_HERO_REAL";
export const UPDATE_HERO_UNDU = "UPDATE_HERO_UNDU";
